# Generated by Django 4.1.7 on 2023-02-24 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pereval_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas', models.CharField(choices=[('EA', 'Планета Земля'), ('PL', 'Памиро-Алай'), ('AL', 'Алтай'), ('SH', 'Северо-Чуйский хребет'), ('YH', 'Южно-Чуйский хребет'), ('KN', 'Катунский хребет'), ('FA', 'Фанские горы'), ('GH', 'Гиссарский хребет (участок западнее перевала Анзоб)'), ('MZ', 'Матчинский горный узел'), ('GK', 'Горный узел Такали, Туркестанский хребет'), ('HI', 'Высокий Алай'), ('KI', 'Кичик-Алай и Восточный Алай'), ('AR', 'Аладаглар'), ('TR', 'Тавр'), ('SI', 'Саяны'), ('LY', 'Хребет Листвяга'), ('II', 'Ивановский хребет'), ('MU', 'Массив Мунгун-Тайга'), ('CN', 'Хребет Цаган-Шибэту'), ('CC', 'Хребет Чихачева (Сайлюгем)'), ('SS', 'Шапшальский хребет'), ('YA', 'Хребет Южный Алтай'), ('MI', 'Хребет Монгольский Алтай'), ('ZY', 'Западный Саян'), ('VY', 'Восточный Саян'), ('AU', 'Кузнецкий Алатау'), ('KA', 'Курайский хребет')], default='EA', max_length=2, verbose_name='Район')),
                ('img', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(choices=[('WR', 'Зима'), ('SG', 'Весна'), ('SR', 'Лето'), ('AN', 'Осень')], default='SR', max_length=2, verbose_name='Сезон')),
                ('activity', models.CharField(choices=[('FT', 'ходьба'), ('SK', 'лыжи'), ('CM', 'катамаран'), ('KK', 'байдарка'), ('RT', 'плот'), ('RG', 'сплав'), ('BC', 'велосипед'), ('CR', 'автомобиль'), ('BK', 'мотоцикл'), ('SL', 'парус'), ('HB', 'верхом')], default='FT', max_length=2, verbose_name='Категория туризма')),
                ('level', models.CharField(choices=[('EY', 'Легкий'), ('TE', 'Умеренный'), ('NL', 'Средний'), ('HD', 'Сложный')], default='EY', max_length=2, verbose_name='Сложность маршрута')),
                ('difficulty', models.CharField(choices=[('AA', '1А'), ('AQ', '2А'), ('AX', '3А'), ('BA', '1Б'), ('BQ', '2Б'), ('BX', '3Б'), ('AT', 'отсутствуют')], default='AT', max_length=2, verbose_name='Сложность перевалов')),
                ('text', models.TextField(max_length=2750, verbose_name='Описание путишествия')),
                ('details', models.BooleanField(default=False, verbose_name='Дополнительные трудности')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NW', 'новая'), ('PG', 'в работе'), ('AD', 'успешно'), ('RJ', 'не принято')], default='NW', max_length=2, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
