# Generated by Django 4.1.7 on 2023-02-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pereval_add',
            options={'verbose_name': 'Подробности путей', 'verbose_name_plural': 'Подробности путей'},
        ),
        migrations.AlterModelOptions(
            name='pereval_images',
            options={'verbose_name': 'Фотографии', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
